import './globals.css'
import { Inter } from 'next/font/google'
import { WalletContextProvider } from '@/components/WalletContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'solana-dapp-1da59a98-dd25-414c-a3f9-e130d25f6c30',
  description: 'Generated by LumAI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletContextProvider>
          {children}
        </WalletContextProvider>
      </body>
    </html>
  )
}